kevin-lee/just-utc

.gitmodules
build.sbt
project/Dependencies.scala

* Removed: scala-hedgehog (git submodule)
* Added: scala-hedgehog (lib)
* Added: Scala 2.10 support

Removed: scala-hedgehog (git submodule)

---

project/plugins.sbt

Changed: plugins.sbt - removed: sbt-devoops repo as it can be downloaded from sbt repo

Changed: plugins.sbt

---

README.md
build.sbt
project/Dependencies.scala
project/ProjectInfo.scala
project/build.properties
project/plugins.sbt

Upgraded: project config - sbt 1.2.8 => 1.3.3 / libs and sbt plugins

Upgrade libs

---

build.sbt

Close #8 - Change group id for publishing to io.kevinlee
* Changed: Group ID: `kevinlee` => `io.kevinlee`
* Added: `homepage` and `scmInfo`

Close #8 - Change group id for publishing to io.kevinlee

---

.github/workflows/build.yml
.github/workflows/release.yml
.github/workflows/sbt-build-simple.sh
.github/workflows/sbt-build.sh
README.md

Close #9 - Set up GitHub Actions for CI

Close #9 - Set up GitHub Actions for CI

---

build.sbt
project/build.properties
project/plugins.sbt

* sbt 1.3.3 => 1.3.7
* sbt-devoops 1.0.0 => 1.0.3

Upgraded: sbt and sbt plugin

---

.github/workflows/build.yml

* Added: cache setup for GitHub Actions
* Changed: separate build configs are replaced with one build with matrix strategy.

GitHub Actions config

---

project/plugins.sbt

Upgraded: sbt-wartremover `2.4.3` => `2.4.5`

Upgraded: sbt-wartremover 2.4.3 => 2.4.5

---

build.sbt
project/ProjectInfo.scala

Upgraded: Scala 2.12.10 => 2.12.11

Upgraded: Scala 2.12.10 => 2.12.11

---

src/test/scala/just/utc/UtcSpec.scala

Improved test with wider UTC Instant range in test input

Improved test with wider UTC Instant range in test input

---

build.sbt
src/main/scala-2.10_2.11/just/utc/CrossVersion.scala
src/main/scala-2.12_2.13/just/utc/CrossVersion.scala

Added: just-fp lib and cross version trait

Added: just-fp lib and cross version trait

---

src/main/scala/just/utc/JDateTimeInUtc.scala
src/test/scala/just/utc/JDateTimeInUtcSpec.scala
src/test/scala/just/utc/UtcSpec.scala

Close #20 - Add error handling to `JDateTimeInUtc.toLocalDateTime`

Close #20 - Add error handling to JDateTimeInUtc.toLocalDateTime

---

src/main/scala/just/utc/DateTimeError.scala
src/main/scala/just/utc/JDateTimeInUtc.scala
src/main/scala/just/utc/Utc.scala

Added: Handling more error cases

Added: Handling more error cases

---

src/main/scala/just/utc/DateTimeError.scala
src/main/scala/just/utc/JDateTimeInUtc.scala
src/main/scala/just/utc/Utc.scala
src/test/scala/just/utc/JDateTimeInUtcSpec.scala

Close #26 - Add error handling to `JDateTimeInUtc.toEpochMilli`

Close #26 - Add error handling to JDateTimeInUtc.toEpochMilli

---

src/main/scala/just/utc/JDateTimeInUtc.scala

Fixed: minor wart issue

---

.github/workflows/build.yml
build.sbt
project/Dependencies.scala
project/build.properties

Upgraded: sbt 1.3.13 => 1.5.2 / Stop supporting Scala 2.10

Upgraded: sbt 1.3.13 => 1.5.2 / Stop supporting Scala 2.10

---

project/build.properties

Upgraded: sbt `1.5.2` => `1.5.3`

Upgraded: sbt 1.5.2 => 1.5.3

---

.github/workflows/build.yml
build.sbt
project/plugins.sbt
src/main/scala-2/just/utc/Utc.scala
src/main/scala-3/just/utc/CrossVersion.scala
src/main/scala-3/just/utc/Utc.scala

Close #32 - Support Scala 3.0.0

Close #32 - Support Scala 3.0.0

---

build.sbt
project/plugins.sbt

Clean up - `build.sbt` and `plugins.sbt`

Clean up - build.sbt and plugins.sbt

---

project/build.properties

Bump sbt to `1.6.2`

---

.scalafmt.conf
src/main/scala-3/just/utc/Utc.scala
src/main/scala/just/utc/DateTimeError.scala
src/main/scala/just/utc/JDateTimeInUtc.scala
src/test/scala/just/utc/JDateTimeInUtcSpec.scala
src/test/scala/just/utc/UtcSpec.scala

* Add `.scalafmt.conf`
* Format the code with the formatting rules in `.scalafmt.conf`

Add `.scalafmt.conf` and format the code

---

src/main/scala-2/just/utc/Utc.scala
src/main/scala-3/just/utc/Utc.scala

Close #39 - Add `epochMillisWithNanos` to `Utc`

Close #39 - Add `epochMillisWithNanos` to `Utc`

---

src/main/scala-2/just/utc/Utc.scala
src/main/scala-3/just/utc/Utc.scala

Close #41 - Update `hashCode` and `equals` in `Utc`

Close #41 - Update `hashCode` and `equals` in `Utc`

---

.github/dependabot.yml
.github/pr-labeler.yml
.github/workflows/pr-labeler.yml

GitHub Actions: auto PR labeling with `pr-labeler.yml` and add `dependabot.yml`

GitHub Actions: auto PR labeling with `pr-labeler.yml` and add `dependabot.yml`

---

build.sbt
project/plugins.sbt

Bump `sbt-devoops` to `3.1.0`

---

.github/workflows/coverage.yml
.github/workflows/sbt-build-all.sh
project/plugins.sbt
src/main/scala-3/just/utc/Utc.scala

GitHub Actions: Add `coverage.yml` for Codecov

GitHub Actions: Add `coverage.yml` for Codecov

---

src/main/scala-2/just/utc/Utc.scala
src/main/scala-3/just/utc/Utc.scala
src/test/scala/just/utc/UtcSpec.scala

Close #57 - Add `Utc.fromInstant(Instant): Utc`

Close #57 - Add `Utc.fromInstant(Instant): Utc`

---

src/test/scala/just/utc/UtcSpec.scala

Close #63 - Add test for `Utc.minute`

Close #63 - Add test for `Utc.minute`

---

src/test/scala/just/utc/UtcSpec.scala

Close #66 - Add test for `Utc.hour`

Close #66 - Add test for `Utc.hour`

---

src/test/scala/just/utc/UtcSpec.scala

Close #68 - Add test for `Utc.dayOfMonth`

Close #68 - Add test for `Utc.dayOfMonth`

---

src/test/scala/just/utc/UtcSpec.scala

Close #70 - Add test for `Utc.month`

Close #70 - Add test for `Utc.month`

---

src/test/scala/just/utc/UtcSpec.scala

Close #72 - Add test for `Utc.dayOfWeek`

Close #72 - Add test for `Utc.dayOfWeek`

---

src/main/scala-2/just/utc/Utc.scala
src/main/scala-3/just/utc/Utc.scala
src/test/scala/just/utc/UtcSpec.scala

Close #73 - Rename `dayOfWeek` in `Utc` to `dayOfWeekValue`

Close #73 - Rename `dayOfWeek` in `Utc` to `dayOfWeekValue`

---

src/main/scala-2/just/utc/Utc.scala
src/main/scala-3/just/utc/Utc.scala
src/test/scala/just/utc/UtcSpec.scala

Close #74 - Rename `dayOfMonth` in `Utc` to `dayOfMonthValue`

Close #74 - Rename `dayOfMonth` in `Utc` to `dayOfMonthValue`

---

src/main/scala-2/just/utc/types/DayOfWeek.scala
src/main/scala-3/just/utc/types/DayOfWeek.scala
src/test/scala/just/utc/types/DayOfWeekSpec.scala

Close #77 - Add `DayOfWeek`

---

src/main/scala-2/just/utc/Utc.scala
src/main/scala-3/just/utc/Utc.scala
src/test/scala/just/utc/UtcSpec.scala

Close #78 - Add `dayOfWeek` returning `DayOfWeek` to `Utc`

Close #78 - Add `dayOfWeek` returning `DayOfWeek` to `Utc`

---

src/main/scala-2/just/utc/types/DayOfWeek.scala
src/main/scala-3/just/utc/types/DayOfWeek.scala

Update: use just-fp more

---

.github/workflows/build.yml
build.sbt
project/build.properties

Bump sbt to `1.10.0`

---

project/plugins.sbt

Bump sbt-wartremover to 2.4.21

Bump sbt-wartremover to 2.4.21

---

.scalafmt.conf

Update scalafmt version to 3.8.1

Update scalafmt version to 3.8.1

---

project/build.properties

Bump sbt to `1.10.1`
